### ISSUE TITLE
Page undefined

### ISSUE THREAD

**Issue by Zeph33** [samyam81/PDF-To-Excel#1]
Hello,
I want to test  PDF-To-Excel, but I got the error
App.go:36:23: pdfDocument.Page undefined (type *fitz.Document has no field or method Page)

**Comment by samyam81** [comment]
The error you're encountering indicates that there's no Page method available directly on pdfDocument of type *fitz.Document. The go-fitz library you are using (github.com/gen2brain/go-fitz) may have been updated or has a different API compared to what the code expects. I will chnage the writeTextBoxesToExcel to Encounter this.

**Comment by samyam81** [comment]
I hope this works as it has been intended to work. Sorry for the inconvenience.
